##################
# For Github User
# github_username: "slack_member_id"

# Chen Yingxue
chenyingxue0124: "U01MMN37ZUZ"
# Huang Siyang
VinoLavine: "U01LUA8P1N3"
# Jiang Xiong
sakuragi1111: "U01MMN17GAV"
# Li yifan
lyfllrr: "U01M2A57JA2"
# Wang Hanqin
whq-hqw: "U01M2A626TY"
# Zhang Yidong
zydmayday: "U01M93KGY3U"

##################
# For Github Team
# github_teamname: "slack_member_id"

coremember: "question_bank_dev"
